from building import *
import rtconfig

cwd = GetCurrentDir()

src = []

src += Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('cloudlib', src, depend = ['RT_USING_CLOUDSDK_LIB'], CPPPATH = CPPPATH)

Return('group')
