
from building import *
import rtconfig

cwd     = GetCurrentDir()
CPPPATH = [cwd]
LOCAL_CCFLAGS = ''

src = ['fal_flash_port.c']

if GetDepend(['BSP_USING_FLASH']):
    src += ['fal_flash_sfud_port.c']

if rtconfig.CROSS_TOOL == 'gcc':
    LOCAL_CCFLAGS += ' -std=c99'
elif rtconfig.CROSS_TOOL == 'keil':
    LOCAL_CCFLAGS += ' --c99'

group = DefineGroup('fal', src, depend = ['PKG_USING_FAL'], CPPPATH = CPPPATH, LOCAL_CCFLAGS = LOCAL_CCFLAGS)

Return('group')
